### ISSUE TITLE
How can I install the "pangeo" environment we are using on Nebari on my own machine?

### ISSUE THREAD

**Issue by rsignell** [OpenScienceComputing/unige-pangeo-course#2]
I always recommend using installing python using the [IOOS Python Instructions](https://ioos.github.io/ioos_code_lab/content/ioos_installation_conda.html), but skipping the installation of the custom IOOS conda environment.   

Instead, use OUR custom `environment.yml`:
``` yaml
name: pangeo
channels:
  - conda-forge
dependencies:
  - python=3.11
  - adlfs
  - aiobotocore
  - birdy
  - black
  - bokeh
  - boto3
  - cdsapi
  - cf_xarray
  - cfgrib
  - cfunits
  - climpred
  - coiled
  - curl
  - dask-geopandas
  - dask
  - datashader
  - datacube
  - dask-geopandas
  - depfinder
  - distributed
  - erddapy
  - fastparquet
  - firefox
  - geckodriver
  - flox
  - folium
  - fsspec>=2024.2.0
  - gcsfs
  - gdal
  - gdptools
  - geocube
  - geogif
  - geolinks
  - geopandas
  - geopy
  - geoviews
  - gifsicle
  - graphviz
  - h5netcdf
  - h5py
  - hologridgen
  - holoviews>=1.18.3
  - htop
  - hvplot
  - imagecodecs
  - intake>=2.0
  - intake-geopandas
  - intake-stac
  - intake-xarray
  - intake-parquet
  - ipykernel
  - ipyleaflet
  - ipywidgets
  - isort
  - jinja2
  - jupyter_bokeh
  - jupyter-panel-proxy
  - jupyterlab_code_formatter
  - jupytext
  - kerchunk
  - jq
  - leafmap
  - lxml
  - lz4
  - mamba
  - metpy
  - nbgitpuller
  - nbstripout
  - nco
  - netcdf4
  - numba
  - numcodecs
  - odc-algo
  - odc-stac
  - openpyxl
  - osmnx
  - owslib
  - pandas == 1.5.3
  - panel
  - pangeo-forge-recipes
  - papermill
  - param
  - pip
  - pint-xarray
  - planetary-computer
  - pyarrow
  - pyarrow-hotfix
  - pyepsg
  - pygeohydro
  - pydaymet
  - pynhd
  - py3dep
  - pygeoogc
  - pygeoutils
  - pynco
  - pyogrio
  - pyvista
  - async_retriever
  - pystac
  - pystac-client
  - python-graphviz
  - python-snappy
  - pyyaml
  - python-gist
  - rasterio
  - rechunker
  - requests
  - rich
  - rio-cogeo
  - rioxarray
  - scikit-image
  - s3fs
  - seaborn
  - seawater
  - selenium
  - siphon
  - spatialpandas
  - stackstac
  - toolz
  - ujson
  - unzip
  - utide
  - vim
  - wgrib2
  - xagg
  - xarray-spatial
  - xarray_leaflet
  - xbitinfo-python
  - xesmf
  - xoak
  - xrviz
  - xskillscore
  - zip
  - zstandard
  - xmip
  - intake-esm
  - xarray-datatree
  - h5pyd
  - noaa-coops
  - kbatch
  - xstac
  - zarr
  - jupyter-book
  - ghp-import
  - jsonschema-with-format-nongpl
  - webcolors
  - pip:
      - earthaccess @ git+https://github.com/nsidc/earthaccess@main
      - pangeo-forge-esgf
      - streamjoy
      - webdriver_manager
      - xarrayutils @ git+https://github.com/rsignell/xarrayutils@patch-1
variables: {}
```
